# HTCondor submit file for running the example LLM agent by serving the LLM via vllm

universe                = vanilla
initialdir              = /nethome/mareikeh/lst_agent_example

executable              = /nethome/mareikeh/lst_agent_example/htcondor_scripts/exec_agent.sh

output                  = /scratch/mareikeh/logs/logs.$(ClusterId).$(ProcId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).out
error                   = /scratch/mareikeh/logs/logs.$(ClusterId).$(ProcId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).err
log                     = /scratch/mareikeh/logs/logs.$(ClusterId).$(ProcId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).log

request_GPUs            = 1
request_CPUs            = 4
request_memory          = 16G
getenv                  = True
requirements            = (GPUs_GlobalMemoryMb >= 80000)
+WantGPUHomeMounted     = true

arguments = 127.0.0.1 8080 Qwen3-8B

queue 1  