# HTCondor submit file for running the example LLM agent by serving the LLM via vllm
# Uses queue syntax to pass multiple argument combinations

universe                = vanilla
initialdir              = /nethome/mareikeh/lst_example_agent

executable              = /nethome/mareikeh/lst_example_agent/htcondor_scripts/exec_agent.sh

output                  = /scratch/hartmann/logs/logs.$(ClusterId).$(ProcId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).out
error                   = /scratch/hartmann/logs/logs.$(ClusterId).$(ProcId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).err
log                     = /scratch/hartmann/logs/logs.$(ClusterId).$(ProcId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).log

request_GPUs            = 1
request_CPUs            = 16
request_memory          = 40G
getenv                  = True
requirements            = (GPUs_GlobalMemoryMb >= 80000) 
#&& (TARGET.Machine != "hopper-3.coli.uni-saarland.de")
+WantGPUHomeMounted     = true
+MaxWallTime            = 604800

#accounting_group = pausable

queue 1  